image: golang:1.8.3-alpine
stages:
  - build
  - test

services:
  - postgres:latest

variables:
  POSTGRES_DB: lmb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - apk add --update git
  - export GOPATH=$(dirname $CI_PROJECT_DIR)/go
  - mkdir -p $GOPATH/src
  - cd $GOPATH/src
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_DIR

build-locatemybeer-staging:
  stage: build
  script:
    - go build

test-locatemybeer-staging:
  stage: test
  script:
    - go build