image: golang:1.8.3
stages:
  - build
  - test

services:
  - postgres:latest

variables:
  POSTGRES_DB: lmb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - echo $GOPATH
  - export GOPATH=$(dirname $CI_PROJECT_DIR)/go
  - echo $GOPATH
  - mkdir -p $GOPATH/src/gitlab.com/locatemybeer/  
  - cd $CI_PROJECT_DIR/..
  - cp -r lmb-back $GOPATH/src/gitlab.com/locatemybeer/  
  - echo $GOPATH/src/gitlab.com/locatemybeer/lmb-back
  - cd $GOPATH/src/gitlab.com/locatemybeer/lmb-back
  - go get -u github.com/Masterminds/glide

build-locatemybeer-staging:
  stage: build
  script:
    - $GOPATH/bin/glide install
    - make build

test-locatemybeer-staging:
  stage: test
  script:
    - $GOPATH/bin/glide install
    - make test
