image: golang:1.8.3
stages:
  - build
  - test
  - deploy

services:
  - postgres:latest

variables:
  POSTGRES_DB: lmb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - echo $PATH
  - export PORT=8080
  - export RESTFUL_DSN=postgres://runner@postgres/lmb?sslmode=disable
  - export GOPATH=$(dirname $CI_PROJECT_DIR)/go
  - mkdir -p $GOPATH/src/gitlab.com/locatemybeer/  
  - cd $CI_PROJECT_DIR/..
  - cp -r lmb-back $GOPATH/src/gitlab.com/locatemybeer/  
  - echo $GOPATH/src/gitlab.com/locatemybeer/lmb-back
  - cd $GOPATH/src/gitlab.com/locatemybeer/lmb-back
  - go get -u github.com/Masterminds/glide

build-locatemybeer-staging:
  stage: build
  script:
    - $GOPATH/bin/glide install
    - make build

test-locatemybeer-staging:
  stage: test
  script:
    - $GOPATH/bin/glide install
    - make test


deploy-locatemybeer-staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y rubygems
    - /usr/bin/gem install dpl
    - dpl --provider=heroku --app=intense-crag-22322 --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master

